[book]
authors = ["Vitalii Perehonchuk"]
language = "uk"
multilingual = false
src = "src"
title = "Фаза затемнення – Eclipse Phase українською"


[build]
create-missing = false

[output.html]
additional-css = ["ep2e.css"]
no-section-label = false
git-repository-url = "https://github.com/undead404/eclipsephase-uk"

[output.html.print]
enable = true

[output.html.fold]
enable = true

[output.html.search]
enable = false
use-boolean-and = true

[preprocessor.writer]
enable = true
command = "node scripts/writer/index.mjs"

# [preprocessor.internal-links-checker]
# enable = false
# command = "node scripts/internal-links-checker/index.mjs"